const AUTHENTICATION = "AUTHENTICATION";
const LOGOUT = "LOGOUT";
const FETCH_ALL_QUIZES = "FETCH_ALL_QUIZES";
const CREATE_QUIZ = "CREATE_QUIZ";
const EDIT_QUIZ = "EDIT_QUIZ";
const DELETE_QUIZ = "DELETE_QUIZ";

export {
    AUTHENTICATION,
    LOGOUT,
    FETCH_ALL_QUIZES,
    CREATE_QUIZ,
    EDIT_QUIZ,
    DELETE_QUIZ 
};